### ISSUE TITLE
Suggestions for refactoring Makefile

### ISSUE THREAD

**Issue by Animesh-Ghosh** [Mr-Sunglasses/Chat-Application-C#1]
Hi

I was looking around the code-base and I thought would I give some suggestions for refactoring the Makefile since I had written a few before (only for personal projects though 😅).

1. Use pattern rules and automatic variables to shorten the Makefile:
`$<` and `$@` seem like good candidates here.

2. Use Makefile variables for the C compiler, common flags etc:
```makefile
CC = gcc

# the above can then be used like so
$(CC) $(FLAGS) client.c -c client
```

I went ahead and did the changes in my fork so that you can see how the [diff](https://github.com/Mr-Sunglasses/Chat-Application-C/compare/master...Animesh-Ghosh:refactor-makefile) looks.

Thanks!

**Comment by Animesh-Ghosh** [comment]
@Mr-Sunglasses let me know if I should go ahead and open a Pull Request.

**Comment by Mr-Sunglasses** [comment]
@Animesh-Ghosh Go ahead will love to see your contribution.

**Comment by Animesh-Ghosh** [comment]
@Mr-Sunglasses created #2.

**Comment by Mr-Sunglasses** [comment]
Thanks, @Animesh-Ghosh for your valuable contribution.
